#!/bin/bash

swayidle -w \
	"$HOME/.config/hypr/scripts/lockscreen" \
	"hyprctl dispatch dpms off" \
	resume "hyprctl dispatch dpms on" \
	before-sleep "$HOME/.config/hypr/scripts/lockscreen" \
	"systemctl suspend"
