#!/bin/bash

swayidle -w \
	timeout 900 "$HOME/.config/hypr/scripts/lockscreen" \
	timeout 1200 "hyprctl dispatch dpms off" \
	resume "hyprctl dispatch dpms on" \
	before-sleep "$HOME/.config/hypr/scripts/lockscreen" \
	timeout 1800 "systemctl suspend"
