#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## launch mako with alt config

# CONFIG="$HOME/.config/dunst/dunstrc"
CONFIG="$HOME/.config/hypr/mako/config"

# if [[ ! $(pidof dunst) ]]; then
# 	dunst -config ${CONFIG}
# fi

if [[ ! $(pidof mako) ]]; then
	mako --config ${CONFIG}
fi
