#!/usr/bin/env bash
# __  ______   ____
# \ \/ /  _ \ / ___|
#  \  /| | | | |  _
#  /  \| |_| | |_| |
# /_/\_\____/ \____|
#
# -----------------------------------------------------
sleep 1

# Kill all possible running xdg-desktop-portals
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-kde
killall xdg-desktop-portal-gtk
killall xdg-desktop-portal
sleep 1

# Start xdg-desktop-portal-gtk
/usr/lib/xdg-desktop-portal-gtk &
sleep 1

# Start xdg-desktop-portal-hyprland
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2

# Start xdg-desktop-portal
/usr/lib/xdg-desktop-portal &
sleep 1
