[font]
size = 12

[font.bold]
# family = "JetBrainsMono Nerd Font"
family = "MesloLGS Nerd Font"

[font.bold_italic]
# family = "JetBrainsMono Nerd Font"
family = "MesloLGS Nerd Font"

[font.italic]
# family = "JetBrainsMono Nerd Font"
family = "MesloLGS Nerd Font"

[font.normal]
# family = "JetBrainsMono Nerd Font"
family = "MesloLGS Nerd Font"
